### ISSUE TITLE
Missing .cproject & .project files in lib_i2s/

### ISSUE THREAD

**Issue by UrushiharaYoome** [xmos/lib_i2s#118]
I found the latest vesion cannot be imported into workspace correctly. Compared with old vesions, I guess it was because .cproject & .project files were missing. 
![new](https://user-images.githubusercontent.com/111268647/184589739-484bb7f8-dd04-4269-9373-3a01f15bcf27.png)
![old](https://user-images.githubusercontent.com/111268647/184589757-01f1b0f4-9d90-43ff-a2bb-29bfaca95133.png)

**Comment by xross** [comment]
We are no longer supporting project files.
