### ISSUE TITLE
test_i2s_index_sequence_slave intermittent failures

### ISSUE THREAD

**Issue by danielpieczko** [xmos/lib_i2s#123]
Intermittent Jenkins develop failures over the last two weeks:
[job 1062](http://srv-bri-jcim0:8080/view/develop/job/XMOS/job/lib_i2s/job/develop/1062/), [job 1058](http://srv-bri-jcim0:8080/view/develop/job/XMOS/job/lib_i2s/job/develop/1058/), [job 1056](http://srv-bri-jcim0:8080/view/develop/job/XMOS/job/lib_i2s/job/develop/1056/), [job 1054](http://srv-bri-jcim0:8080/view/develop/job/XMOS/job/lib_i2s/job/develop/1054/), [job 1053](http://srv-bri-jcim0:8080/view/develop/job/XMOS/job/lib_i2s/job/develop/1053/), [job 1051](http://srv-bri-jcim0:8080/view/develop/job/XMOS/job/lib_i2s/job/develop/1051/), [job 1049](http://srv-bri-jcim0:8080/view/develop/job/XMOS/job/lib_i2s/job/develop/1049/)

Test failures can occur on XS2 and XS3 for the following:
 - test_slave_index_sequence.test_i2s_index_sequence_slave[0ch_in,4ch_out]
 - test_slave_index_sequence.test_i2s_index_sequence_slave[4ch_in,0ch_out]
 - test_slave_index_sequence.test_i2s_index_sequence_slave[4ch_in,4ch_out]

The errors are that the output is shorter than expected, so they typically look something like this:
```
AssertionError: Length of output (2 lines) less than expected (5 lines) 
['I', 'R0 R2 R4 R6 R1 R3 R5 R7'] 
['I', 'R0 R2 R4 R6 R1 R3 R5 R7 R0 R2 R4 R6 R1 R3 R5 R7 R0 R2 R4 R6 R1 R3 R5 R7 R0 R2 R4 R6 R1 R3 R5 R7', 'I', 'R0 R2 R4 R6 R1 R3 R5 R7 R0 R2 R4 R6 R1 R3 R5 R7 R0 R2 R4 R6 R1 R3 R5 R7 R0 R2 R4 R6 R1 R3 R5 R7', 'I']
```

**Comment by lucianomartin** [comment]
I made at least 5 Jenkins runs with tools 15.2.1, and they all failed with the error reported in this issue.

**Comment by lucianomartin** [comment]
In #132 I replaced the old MAC Jenkins agents with newer Ubuntu agents, and the problem seems to be fixed. We witnessed 5 successful runs.
I will close this issue for now, and we can reopen it if the problem reappears.
