### ISSUE TITLE
Building for xmos AI boards fails

### ISSUE THREAD

**Issue by PelleS0205** [xmos/lib_i2s#124]
**Issues:**
Compiling with target set to XK-EVK-XU316 or XCORE-AI-EXPLORER raises the following error:

../src/main.xc:218:17: error: unknown function identifier `i2c_master_single_port' (possibly missing prototype?)
    on tile[0]: i2c_master_single_port(i_i2c, 1, p_i2c, 10, 0, 1, 0);

The error occurs during compilation of any example.

**Comment by xross** [comment]
Be sure to have www.github.com/xmos/lib_i2c in your workspace.

We are working on a new dependency getting system.

**Comment by PelleS0205** [comment]
I did get it working eventually. I'm not exactly sure what fixed it, but I believe the fault was on my end. Thank you for the follow-up, Ross.
