### ISSUE TITLE
LR clock port configured as out port in I2S slave

### ISSUE THREAD

**Issue by xross** [xmos/lib_i2s#15]
static void i2s_slave_init_ports(..)

...
    configure_out_port(p_lrclk, bclk, 1);

**Comment by xross** [comment]
Presumably should be:
configure_in_port(p_lrclk, bclk);

**Comment by xross** [comment]
Resolved.

**Comment by ahogen** [comment]
This thread literally helps noone. 

What source file? What line? Why?

**Comment by pthedinger** [comment]
The fix is in:
  lib_i2s/src/i2s_slave_impl.h:18

And the commit that included the fix was:
  https://github.com/xmos/lib_i2s/commit/a2503e8111dd5aede987cf2d6cc4a16f0f7a6ccb

Hope that helps.
