### ISSUE TITLE
16kHz not supported

### ISSUE THREAD

**Issue by andrewstanfordjason** [xmos/lib_i2s#19]
the divider cannot achieve 16kHz which is really common for voice applications

**Comment by ed-xmos** [comment]
The newly added i2s_frame_master() can support this. As long as the BCLK can be divided from the MCLK using the clock block then all should be fine.

Eg. 12.288MHz / 1.024MHz = (6 x 2) -> Sorted

**Comment by ThomasGmeinder** [comment]
Indeed :)
I have changed the application to use i2s_frame_master instead of i2s_master the whole Audio path PDM -> I2S is now working at 16 kHz.

**Comment by samchesney** [comment]
Reopening this issue as it is not clear from the documentation that 16KHz is supported.
The [Master speeds and performance](https://github.com/xmos/lib_i2s/blob/master/lib_i2s/doc/rst/i2s.rst#i2s-master-speeds-and-performance) section does not list support for any sample frequencies below 48kHz, and does not highlight any differences the supported rates of the various master implementations.

**Comment by ed-xmos** [comment]
This can be close now due to https://github.com/xmos/lib_i2s/pull/45

**Comment by samchesney** [comment]
Thank you @ed-xmos
