### ISSUE TITLE
Possible bad description of tdm_config_t parameter offset

### ISSUE THREAD

**Issue by akp7** [xmos/lib_i2s#20]
Description is "The number of bits that the FSYNC signal transitions before the data. Must be a value between 0 and 31." However, this value is set to -1 in AN00203_gige_avb_tdm_demo (1.0.3) file main.xc line 114.

**Comment by pthedinger** [comment]
You are right. It looks like the code copes with an offset value of between -31 and 31, not 0 to 31 as specified in the comment. Thanks for reporting that.

**Comment by pthedinger** [comment]
This is resolved now.
