### ISSUE TITLE
TDM slave

### ISSUE THREAD

**Issue by albanoandrea** [xmos/lib_i2s#21]
Starting from I2S slave, I've written a TDM slave implementation.

It still doesn't support sync_len!=1 and offset !=0.
It has been tested for 2, 4 and 8 channels.

[tdm_slave_impl.h.txt](https://github.com/xmos/lib_i2s/files/525132/tdm_slave_impl.h.txt)

**Comment by ed-xmos** [comment]
Nice work - thanks for submitting. What testing have you done so far (simulator/hardware if so setup/frequency)? 
We should think about what needs to happen to get it integrated into the library.

**Comment by mstaack** [comment]
@mbanth  has there been some movement regarding TDM slave feature for this lib?

will the x200 be able to convert an input tdm stream into usb/adat output?

cheers

**Comment by mstaack** [comment]
@lucianomartin  are there any plans regarding examples for tdm slave usage?
github repo has seen some activity lately ❤️

**Comment by mstaack** [comment]
any news on tdm slave?

**Comment by xross** [comment]
> @lucianomartin are there any plans regarding examples for tdm slave usage?
> github repo has seen some activity lately ❤️

**Comment by xross** [comment]
> > will the x200 be able to convert an input tdm stream into usb/adat output?
> 
> The USB Audio reference design will see a refreshed release soon. This includes support for TDM slave.
> 
> At this point consider xCORE.AI over xCORE200

I should clarify, this has it's own implementation of I2S and doesn't use lib_i2s.

**Comment by ed-xmos** [comment]
Note there is also a working and tested TDM slave implementation here https://github.com/xmos/fwk_io/blob/develop/modules/i2s/api/i2s_tdm_slave.h
