### ISSUE TITLE
tdm_test failure

### ISSUE THREAD

**Issue by samchesney** [xmos/lib_i2s#27]
Looks like something is going wrong in the tdm_test, with the following output seen:
```
TDM Master Checker Started
CONFIG: sample rate: 48000	SCLK: 12288000	num ins 1,	num outs:1, is i2s justified: 0	sclk_edge_count 1	channels_per_data_line: 8
rx error 00000003 00000000
rx error 00000004 00000000
rx error 00000005 00000000
rx error 00000006 00000000
rx error 00000007 00000000
rx error 00000008 00000000
rx error 00000009 00000000
rx error 0000000a 00000000
0, 1
rx error 0000000b 00000000
rx error 0000000c 00000000
rx error 0000000d 0000003f
rx error 0000000e ffffffff
rx error 0000000f ffffffff
rx error 00000010 ffffffff
rx error 00000011 ffffffff
rx error 00000012 ffffffff
rx error 00000013 ffffffff
rx error 00000014 ffffffff
rx error 00000015 ffffffff
rx error 00000016 ffffffff
rx error 00000017 ffffffff
rx error 00000018 ffffffff
rx error 00000019 ffffffff
rx error 0000001a ffffffff
rx error 0000001b ffffffff
-2147483642, 2
rx error 0000001c ffffffff
rx error 0000001d ffffffff
rx error 0000001e 00000004
rx error 0000001f 00000000
14, 3
15, 4
Simulator timed out
```

**Comment by ed-xmos** [comment]
To re-create this, use:

python runtests.py --subtest test_i2s_tdm_tdm.py       
Running tests in 'test_i2s_tdm_tdm.py'

Still seems to be an issue.

**Comment by ed-xmos** [comment]
This looks like a compiler related issue. The input is somehow being optimised away so the data never makes it to the callback from the port. The following change to i2s_tdm_do_tdm_in() in i2s_tdm_master_impl.h fixes the issue.

      size_t chan_num =
        tdm_chan_offset_in + i*channels_per_data_line + prev_fsync_index;
      **//asm volatile("in %0, res[%1]":"=r"(data):"r"(tdm_din[i]):"memory");**
      **tdm_din[i] :> data;**
      i2s_i.receive(chan_num, bitrev(data));

**Comment by ed-xmos** [comment]
Attached is failing sim trace (using asm volatile in) and passing trace case (using :>). Both are filtered for just thread 1. 

Both appear to be executing an input OK. Key is to search for RESID 0x10f00 which is XS1_PORT_1P, the tdm_din port. However captured data is different so test fails using "asm volatile in"

[trace_fail.txt](https://github.com/xmos/lib_i2s/files/1943381/trace_fail.txt)
[trace_ok.txt](https://github.com/xmos/lib_i2s/files/1943382/trace_ok.txt)

**Comment by pthedinger** [comment]
No longer relevant with version 3.0.0 of the library.
