### ISSUE TITLE
DOxygen build warnings 

### ISSUE THREAD

**Issue by xross** [xmos/lib_i2s#32]
Warning: argument 'num_out' of command @param is not found in the argument list of i2s_frame_callback_if::receive(size_t num_in, int32_t samples[num_in])
    Warning: argument 'p_dout' of command @param is not found in the argument list of i2s_master(client i2s_callback_if i2s_i, out buffered___port___port___32(&?p_dout)[num_out], static const size_t num_out, in buffered___port___port___32(&?p_din)[num_in], static const size_t num_in, out buffered ___port___port___32 p_bclk, out buffered ___port___port___32 p_lrclk, clock bclk, const clock mclk)

Warning: argument 'p_din' of command @param is not found in the argument list of i2s_master(client i2s_callback_if i2s_i, out buffered___port___port___32(&?p_dout)[num_out], static const size_t num_out, in buffered___port___port___32(&?p_din)[num_in], static const size_t num_in, out buffered ___port___port___32 p_bclk, out buffered ___port___port___32 p_lrclk, clock bclk, const clock mclk)

Warning: argument 'p_dout' of command @param is not found in the argument list of i2s_frame_master(client i2s_frame_callback_if i2s_i, out buffered___port___port___32(&?p_dout)[num_out], static const size_t num_out, in buffered___port___port___32(&?p_din)[num_in], static const size_t num_in, out port p_bclk, out buffered ___port___port___32 p_lrclk, in port p_mclk, clock bclk)

Warning: argument 'p_din' of command @param is not found in the argument list of i2s_frame_master(client i2s_frame_callback_if i2s_i, out buffered___port___port___32(&?p_dout)[num_out], static const size_t num_out, in buffered___port___port___32(&?p_din)[num_in], static const size_t num_in, out port p_bclk, out buffered ___port___port___32 p_lrclk, in port p_mclk, clock bclk)
    
Warning: argument 'p_dout' of command @param is not found in the argument list of i2s_slave(client i2s_callback_if i2s_i, out buffered___port___port___32(&?p_dout)[num_out], static const size_t num_out, in buffered___port___port___32(&?p_din)[num_in], static const size_t num_in, in port p_bclk, in buffered ___port___port___32 p_lrclk, clock bclk)
    
Warning: argument 'p_din' of command @param is not found in the argument list of i2s_slave(client i2s_callback_if i2s_i, out buffered___port___port___32(&?p_dout)[num_out], static const size_t num_out, in buffered___port___port___32(&?p_din)[num_in], static const size_t num_in, in port p_bclk, in buffered ___port___port___32 p_lrclk, clock bclk)
    
Warning: argument 'p_dout' of command @param is not found in the argument list of tdm_master(client interface i2s_callback_if tdm_i, out buffered ___port___port___32 p_fsync, out buffered___port___port___32(&?p_dout)[num_out], size_t num_out, in buffered___port___port___32(&?p_din)[num_in], size_t num_in, clock clk)
    
Warning: argument 'p_din' of command @param is not found in the argument list of tdm_master(client interface i2s_callback_if tdm_i, out buffered ___port___port___32 p_fsync, out buffered___port___port___32(&?p_dout)[num_out], size_t num_out, in buffered___port___port___32(&?p_din)[num_in], size_t num_in, clock clk)

**Comment by ed-xmos** [comment]
This looks to be related to doxygen not understanding reference and/or nullable prefixes on variable names. I tried to fix this here using spacing or using the ref/nullable name but it didn't work.

Documents appear to render OK.

Suspect it's a tools/xdoc issue.

**Comment by pthedinger** [comment]
This is a known xdoc limitation.

**Comment by mbanth** [comment]
Given @pthedinger's comment that this issue stems from a known xdoc limitation and the fact that xdoc use is deprecated, I cannot justify allocating any engineering effort to fixing it.  Consequently, I'm closing this issue.
