### ISSUE TITLE
Warnings from .cproject file

### ISSUE THREAD

**Issue by ahogen** [xmos/lib_i2s#35]
Lots of unnecessary warnings generated because of entries in the `.cproject` file. Some (I think most) are listed below

- https://github.com/xmos/lib_i2s/blob/f3a10a6019934b3d4757318cc3a69a4426a900d9/lib_i2s/.cproject#L48-L51
- https://github.com/xmos/lib_i2s/blob/f3a10a6019934b3d4757318cc3a69a4426a900d9/lib_i2s/.cproject#L58-L75
- https://github.com/xmos/lib_i2s/blob/f3a10a6019934b3d4757318cc3a69a4426a900d9/lib_i2s/.cproject#L591-L594
- https://github.com/xmos/lib_i2s/blob/f3a10a6019934b3d4757318cc3a69a4426a900d9/lib_i2s/.cproject#L931-L936

Generates the following warnings. Very obnoxious for users.

![capture](https://user-images.githubusercontent.com/6827790/29845627-7b7cf48e-8cc8-11e7-87e6-2a619efeb7a6.PNG)

**Comment by ACascarino** [comment]
As support for xTimeComposer Studio has been scaled back as of the 15.x release, this issue is no longer relevant.
