### ISSUE TITLE
I2S mode vs LEFT_JUSTIFIED, LRCLK may need to be inverted

### ISSUE THREAD

**Issue by henkmuller** [xmos/lib_i2s#43]
The CS43L21 codec <http://www.mouser.com/ds/2/76/CS43L21_F1-472991.pdf> uses '0' to indicate Left (I2S mode), or '1' to indicate Left (LEFT_JUSTIFIED). [Pages 30 and 31]

I think that I2S master/slave library always use '0' to indicate left.

**Comment by ACascarino** [comment]
Closing as per conversation with @henkmuller - if an observed issue reoccurs please reopen this issue with some details!
