### ISSUE TITLE
examples/AN00162_i2s_loopback_demo Application Note not compliant

### ISSUE THREAD

**Issue by DaveAtkinsonXMOS** [xmos/lib_i2s#78]
**Issues:**

 - xdoc-custom RST directives used in the Application Note README
 - application note code not compiling for xcore-ai
 - application note code not running successfully on xcore-ai
 - two spelling mistakes
  - Section 2 i2S loopback demo, sub-section 2.1 "to you Makefile" should read "to your Makefile"
  - Section 2 i2S loopback demo, sub-section 2.3 "efficiently generate clock singal that" should read "efficiently generate clock signal that"

The code in this application note specifically mentions initialising the Cirrus CS5268 and CS4384 codec chips on the XCORE-200 Multimedia Audio Platform, and as such is not directly applicable to the XCORE.ai. Perhaps it would just be sufficient to rename the note to indicate the hardware platform required, and write a different not for the XCORE.ai, or a hardware-independant version?

**Comment by ed-xmos** [comment]
These have all been addressed with https://github.com/xmos/lib_i2s/pull/79/files
