### ISSUE TITLE
Missing tests for xcore AI

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_i2s#81]
Only backpressure test and AN00162 compile and run on xcore AI hardware in Jenkins. The other tests require in depth usage of xmostest and xsim. So even running them on the xcore AI HW target is not really helpful. The best we could do is run these using an xcore AI xsim target, which *should* be fine. Given these run successfully on xcore 200 target already, the risk to not having these is very low. The missing tests  are:

test_basic_frame_master.py
test_basic_frame_master_external_clock.py
test_basic_frame_slave.py
test_basic_master.py
test_basic_slave.py
test_index_sequence.py
test_slave_bclk_invert.py
test_slave_index_sequence.py
test_tdm_index_sequence.py
test_tdm_master_cb.py

In addition, the following following examples are not built under XS3 (or tested to see if they can be downloaded)

app_i2s_frame_loopback_demo
app_i2s_frame_slave_loopback_demo
app_simple_i2s_frame_master
app_simple_i2s_frame_master_external_clock
app_simple_i2s_frame_slave
app_simple_i2s_master
app_simple_i2s_slave
app_simple_tdm_master
app_tdm_loopback_demo

**Comment by ACascarino** [comment]
To complete in tandem with #104
