### ISSUE TITLE
Example does not import correctly into XtimeCOMPOSER

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_i2s#9]
As per above - example is listed and appears to follow the import steps OK but nothing is imported.
This may be due to the pipe character |I2S|.

**Comment by samchesney** [comment]
I think this probably does come from the pipe characters - I've had a quick look to see if I could work out what was going on and think the the inconsistent behaviour I've seen probably stems from pipe characters being illegal in file paths some contexts (e.g. Windows) but acceptable on OS X.

Things I've noticed running xTIMEcomposer on OS X:
* This issue only appears when performing the import via the "Examples" perspective
  * The zip of the example is downloaded and cached by xTIMEcomposer
    * Attempting to import this cached download as an "Archive File" seems to work (requires an existing project in your workspace)
    * Unzipping this cached version manually and then importing the result as an "Existing Projects into Workspace" seems to work
  * Downloading the zip from the website and importing manually as an "Archive File" seems to work (requires an existing project in your workspace)

**Comment by ed-xmos** [comment]
Hi - this didn't fix it for me. I deleted the ~/.xmos/cache folder and tried a fresh import in 14.2.0 and it still failed silently..
